import Ast.UniversalIR
import Parser.HumanParser
import Codegen.ToLean

def main (args : List String) : IO UInt32 := do
  ...
  match Parser.UniversalParser.parseProgram input with
  | .error msg => ...
  | .ok humanAst =>
      let result ← UniversalIR.evalProgram humanAst (λ_ => none)
      ...
      let leanCode ← Codegen.ToLean.fromHuman humanAst
      ...
